CREATE TABLE [dbo].[DATA_FILE] (
    [Id]        INT            IDENTITY (1, 1) NOT NULL,
    [NAME]      NVARCHAR (MAX) NULL,
    [STATUS]    INT            NOT NULL,
    [LAST_LINE] INT            NOT NULL,
    CONSTRAINT [PK_dbo.DATA_FILE] PRIMARY KEY CLUSTERED ([Id] ASC)
);

CREATE TABLE [dbo].[DATA_LINE] (
    [Id]          INT            IDENTITY (1, 1) NOT NULL,
    [TIME]        DATETIME       NOT NULL,
    [VALUE]       INT            NOT NULL,
    [ORIGIN]      NVARCHAR (MAX) NULL,
    [ID_DATAFILE] INT            NOT NULL,
    CONSTRAINT [PK_dbo.DATA_LINE] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_dbo.DATA_LINE_dbo.DATA_FILE_ID_DATAFILE] FOREIGN KEY ([ID_DATAFILE]) REFERENCES [dbo].[DATA_FILE] ([Id]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_ID_DATAFILE]
    ON [dbo].[DATA_LINE]([ID_DATAFILE] ASC);